#!/bin/bash

##########################################################################################
# Utils Function
##########################################################################################

exit_err () {
	echo "\033[1;31m $1 \033[0m\n"
	exit 1
}

if [ $# -gt 4 ] || [ $# -lt 4 ]; then
	exit_err "Invalid number of arguments !\n"
fi

for (( value = 1; value <= $1; value++))
do
    echo $2, $3, $4
    screen -dm bash -c "./zappy_ai -p $2 -n $3 -h $4"
done

exit 0